/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package itte;

import itte.clases.modelos.Cursos;
import itte.clases.modelos.CursosNombres;
import itte.clases.Funciones;
import itte.clases.modelos.Horarios;
import itte.clases.modelos.Profesores;
import java.awt.Color;
import java.awt.Component;
import java.awt.Frame;
import java.awt.HeadlessException;
import java.lang.reflect.InvocationTargetException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import org.jdesktop.swingx.JXDatePicker;

/**
 *
 * @author Juan M S
 */
public class PanelCursos extends javax.swing.JPanel {


    
    /**
     * Creates new form PanelCursos
     */
    public PanelCursos() {
        initComponents();
    }
    
    
    private void abrirDialogoSelecColor(JTextField jtf) {
        DialogoSelectColor dialogoSelecColor = new DialogoSelectColor();
        dialogoSelecColor.setTitle("Selección Color");
        dialogoSelecColor.aux = jtf;
        dialogoSelecColor.pack();
        dialogoSelecColor.setAlwaysOnTop(true);
        dialogoSelecColor.setModal(true);
        dialogoSelecColor.setLocationRelativeTo(this);
        dialogoSelecColor.setVisible(true);
        
    }
    

    private void setearDatePicker(JXDatePicker jxdp){
        jxdp.setDate(new java.sql.Date((Calendar.getInstance()).getTimeInMillis()));

        jxdp.setFormats(new SimpleDateFormat("yyyy-MM-dd"));

        jxdp.setTimeZone(TimeZone.getTimeZone("America/Argentina/Buenos_Aires"));
    }
    
    private void armarLista(List<String> lista, JList<String> jList, JScrollPane jScrollPane) {
        jList.setModel(new javax.swing.AbstractListModel<String>() {
            public int getSize() {
                return lista.size();
            }

            public String getElementAt(int i) {
                return lista.get(i);
            }
        });
        jScrollPane.setViewportView(jList);
    }
    
    public void obtenerCursos() throws HeadlessException {
        Cursos cursos = new Cursos();
        String aC = CursosSelecAnioParaCursos.getSelection().getActionCommand();
        cursos.obtenerCursosSegunAnio(aC);
        List<String> lista = new ArrayList<String>();
        while (cursos.sig()) {
                String item = !aC.equals("Todos")?(cursos.getNombre()+" <"+cursos.getId_curso()+">"):(cursos.getNombre()+" ("+cursos.getObservaciones()+")"+" <"+cursos.getId_curso()+">");
                lista.add(item);
        }
        armarLista(lista,CursosjList2,jScrollPane3);
    }
    
    public void obtenerNombresCursosParaComboBox () {
        CursosNombres cursosNombres = new CursosNombres();
        int cantNombres = cursosNombres.obtenerCantidad(), i = 0;
        String nombresCursos [] = new String [cantNombres];
        cursosNombres.obtenerTodos();
        while (cursosNombres.sig()) {
                nombresCursos[i++] = cursosNombres.getNombre();
        }
        CursosCBNombreCurso.setModel(new javax.swing.DefaultComboBoxModel<String>(nombresCursos));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CursosSelecAnioParaCursos = new javax.swing.ButtonGroup();
        tabCursos = new javax.swing.JPanel();
        CursosjTabbCursos = new javax.swing.JTabbedPane();
        CursosjPanel4 = new javax.swing.JPanel();
        CursosjPanel8 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        CursosCBNombreCurso = new javax.swing.JComboBox<>();
        CursosagregarCursoBtn = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        CursoscargaHorariaHorasTxt = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        CursoscargaHorariaMinutosTxt = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        CursosduracionCursoMesesTxt = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        CursoscuotaSugeridaTxt = new javax.swing.JTextField();
        CursoscantidadCuotasTxt = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        cursosRbAnioActual = new javax.swing.JRadioButton();
        cursosRbAnioSig = new javax.swing.JRadioButton();
        cursosRbAnioAnt = new javax.swing.JRadioButton();
        cursosRbTodos = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        CursosjList2 = new javax.swing.JList<>();
        jPanel10 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        CursosjCheckBox1 = new javax.swing.JCheckBox();
        jXDatePicker4 = new org.jdesktop.swingx.JXDatePicker();
        jXDatePicker5 = new org.jdesktop.swingx.JXDatePicker();
        jPanel11 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        CursostituloTxt = new javax.swing.JTextField();
        CursosrequisitosPrvTxt = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        CursoscostoInscripcionTxt = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        CursosgProfesorTxt = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        CursoscolorFondoTxt = new javax.swing.JTextField();
        CursoscolorFondoBtn = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        CursoscolorFuenteTxt = new javax.swing.JTextField();
        CursoscolorFuenteBtn = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        CursoscapacidadAulaTxt = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        CursosCBCicloLectivo = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        CursosverAlumnosAfectadosBtn = new javax.swing.JButton();
        CursosaceptarCargarBtn = new javax.swing.JButton();
        CursosrestablecerBtn = new javax.swing.JButton();
        CursosguardarBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel108 = new javax.swing.JLabel();
        CursosCBHorarios = new javax.swing.JComboBox();
        jLabel51 = new javax.swing.JLabel();
        CursosCBProfesores = new javax.swing.JComboBox();
        jLabel109 = new javax.swing.JLabel();
        CursosCBDias = new javax.swing.JComboBox();
        CursosTxtHorarioDesdeHora = new javax.swing.JTextField();
        jLabel110 = new javax.swing.JLabel();
        CursosTxtHorarioDesdeMinutos = new javax.swing.JTextField();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        CursosTxtHorarioHastaHora = new javax.swing.JTextField();
        jLabel113 = new javax.swing.JLabel();
        CursosTxtHorarioHastaMinutos = new javax.swing.JTextField();
        CursosBtnHorarioNuevo = new javax.swing.JButton();
        CursosCheckAnexarHorarioACurso = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();

        CursosSelecAnioParaCursos.add(cursosRbAnioActual);
        CursosSelecAnioParaCursos.add(cursosRbAnioAnt);
        CursosSelecAnioParaCursos.add(cursosRbAnioSig);
        CursosSelecAnioParaCursos.add(cursosRbTodos);

        CursosjPanel4.setBackground(new java.awt.Color(255, 255, 255));

        CursosjPanel8.setBackground(new java.awt.Color(255, 204, 204));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel32.setText("Nombre Curso*");

        CursosCBNombreCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CursosagregarCursoBtn.setText("+");

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel33.setText("Carga Horaria Semanal");

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel34.setText("Duración del Curso");

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel35.setText("Cuota Sugerida*");

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel36.setText("Cantidad de Cuotas");

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel38.setText("Horas");

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel39.setText("Minutos");

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel40.setText("Meses");

        javax.swing.GroupLayout CursosjPanel8Layout = new javax.swing.GroupLayout(CursosjPanel8);
        CursosjPanel8.setLayout(CursosjPanel8Layout);
        CursosjPanel8Layout.setHorizontalGroup(
            CursosjPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CursosjPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CursosjPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CursosjPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CursosCBNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CursosagregarCursoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(CursosjPanel8Layout.createSequentialGroup()
                        .addGroup(CursosjPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CursosjPanel8Layout.createSequentialGroup()
                                .addComponent(CursoscargaHorariaHorasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CursoscargaHorariaMinutosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel39)
                                .addGap(18, 18, 18)
                                .addComponent(CursosduracionCursoMesesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel40))
                            .addGroup(CursosjPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel34)))
                        .addGap(26, 26, 26)
                        .addGroup(CursosjPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addGroup(CursosjPanel8Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(CursoscuotaSugeridaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(CursosjPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CursosjPanel8Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(CursoscantidadCuotasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        CursosjPanel8Layout.setVerticalGroup(
            CursosjPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CursosjPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CursosjPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(CursosCBNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CursosagregarCursoBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CursosjPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(CursosjPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CursosjPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CursoscuotaSugeridaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CursoscantidadCuotasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CursosjPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CursosduracionCursoMesesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel40))
                    .addGroup(CursosjPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CursoscargaHorariaMinutosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel39))
                    .addGroup(CursosjPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CursoscargaHorariaHorasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel38)))
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(0, 102, 255));

        cursosRbAnioActual.setBackground(new java.awt.Color(255, 0, 0));
        cursosRbAnioActual.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        cursosRbAnioActual.setForeground(new java.awt.Color(240, 240, 240));
        cursosRbAnioActual.setSelected(true);
        cursosRbAnioActual.setText("2015");
        cursosRbAnioActual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cursosRbAnioActualMouseClicked(evt);
            }
        });
        cursosRbAnioActual.setActionCommand(cursosRbAnioActual.getText());

        cursosRbAnioSig.setBackground(new java.awt.Color(0, 102, 255));
        cursosRbAnioSig.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        cursosRbAnioSig.setForeground(new java.awt.Color(240, 240, 240));
        cursosRbAnioSig.setText("2016");
        cursosRbAnioSig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cursosRbAnioSigMouseClicked(evt);
            }
        });
        cursosRbAnioSig.setActionCommand(cursosRbAnioSig.getText());

        cursosRbAnioAnt.setBackground(new java.awt.Color(0, 102, 255));
        cursosRbAnioAnt.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        cursosRbAnioAnt.setForeground(new java.awt.Color(240, 240, 240));
        cursosRbAnioAnt.setText("2014");
        cursosRbAnioAnt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cursosRbAnioAntMouseClicked(evt);
            }
        });
        cursosRbAnioAnt.setActionCommand(cursosRbAnioAnt.getText());

        cursosRbTodos.setBackground(new java.awt.Color(0, 102, 255));
        cursosRbTodos.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        cursosRbTodos.setForeground(new java.awt.Color(240, 240, 240));
        cursosRbTodos.setText("Todos");
        cursosRbTodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cursosRbTodosMouseClicked(evt);
            }
        });
        cursosRbTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursosRbTodosActionPerformed(evt);
            }
        });
        cursosRbTodos.setActionCommand(cursosRbTodos.getText());

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cursosRbAnioActual)
                .addGap(10, 10, 10)
                .addComponent(cursosRbAnioSig)
                .addGap(10, 10, 10)
                .addComponent(cursosRbAnioAnt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cursosRbTodos)
                .addGap(14, 14, 14))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cursosRbAnioActual)
                    .addComponent(cursosRbAnioSig)
                    .addComponent(cursosRbAnioAnt)
                    .addComponent(cursosRbTodos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CursosjList2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CursosjList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        CursosjList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CursosjList2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(CursosjList2);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel37.setText("Fecha Inicio");

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel41.setText("Fecha Finalización");

        CursosjCheckBox1.setText("Activo");

        setearDatePicker(jXDatePicker4);

        setearDatePicker(jXDatePicker5);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(jXDatePicker4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jXDatePicker5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(CursosjCheckBox1)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CursosjCheckBox1)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37)
                            .addComponent(jLabel41))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jXDatePicker4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXDatePicker5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)))
                .addGap(32, 32, 32))
        );

        jPanel11.setBackground(new java.awt.Color(255, 204, 204));

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel42.setText("Titulo*");

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel43.setText("Requisitos Previos");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42)
                    .addComponent(CursostituloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel43)
                    .addComponent(CursosrequisitosPrvTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CursosrequisitosPrvTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CursostituloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1))
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel44.setText("Costo Inscripción");

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel45.setText("$");

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel46.setText("G. Profesor");

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel47.setText("Color Fondo");

        CursoscolorFondoTxt.setEditable(false);

        CursoscolorFondoBtn.setText("Color");
        CursoscolorFondoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CursoscolorFondoBtnActionPerformed(evt);
            }
        });

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel48.setText("Color Fuente");

        CursoscolorFuenteTxt.setEditable(false);

        CursoscolorFuenteBtn.setText("Color");
        CursoscolorFuenteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CursoscolorFuenteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel44)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CursoscostoInscripcionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(79, 79, 79)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CursosgProfesorTxt)
                    .addComponent(jLabel46))
                .addGap(39, 39, 39)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel47)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(CursoscolorFondoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CursoscolorFondoBtn)))
                .addGap(22, 22, 22)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel48)
                        .addGap(82, 82, 82))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(CursoscolorFuenteTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CursoscolorFuenteBtn)
                        .addContainerGap())))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel48)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CursoscolorFuenteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CursoscolorFuenteBtn)))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44)
                            .addComponent(jLabel46)
                            .addComponent(jLabel47))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel45)
                            .addComponent(CursoscostoInscripcionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CursosgProfesorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CursoscolorFondoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CursoscolorFondoBtn))))
                .addGap(28, 28, 28))
        );

        jPanel13.setBackground(new java.awt.Color(255, 204, 204));

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 153));
        jLabel49.setText("Capacidad del Aula*");

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 0, 153));
        jLabel50.setText("Ciclo Lectivo");

        CursosCBCicloLectivo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { String.valueOf(Funciones.getAnio(true)), String.valueOf(Funciones.getAnio(true)-1), String.valueOf(Funciones.getAnio(true)+1), String.valueOf(Funciones.getAnio(true)+2) }));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel49)
                    .addComponent(CursoscapacidadAulaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(172, 172, 172)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel50)
                    .addComponent(CursosCBCicloLectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel49)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CursoscapacidadAulaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel50)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CursosCBCicloLectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2))
        );

        CursosverAlumnosAfectadosBtn.setText("Ver alumnos afectados al g_profesor");

        CursosaceptarCargarBtn.setText("Aceptar y Cargar Horario");
        CursosaceptarCargarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CursosaceptarCargarBtnActionPerformed(evt);
            }
        });

        CursosrestablecerBtn.setText("Restablecer");
        CursosrestablecerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CursosrestablecerBtnActionPerformed(evt);
            }
        });

        CursosguardarBtn.setBackground(new java.awt.Color(255, 0, 0));
        CursosguardarBtn.setForeground(new java.awt.Color(255, 255, 255));
        CursosguardarBtn.setText("GUARDAR");
        CursosguardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CursosguardarBtnActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 102));

        jLabel108.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel108.setForeground(new java.awt.Color(0, 0, 153));
        jLabel108.setText("Horarios");

        CursosCBHorarios.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));

        jLabel51.setText("Profesor");

        try{
            CursosCBProfesores.setModel(new javax.swing.DefaultComboBoxModel((new Profesores()).obtenerTodosNombres(true)));
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

        jLabel109.setText("Día");

        CursosCBDias.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Lunes","Martes","Miercoles","Jueves","Sabados","Domingos"}));

        CursosTxtHorarioDesdeHora.setText("13");

        jLabel110.setText(":");

        CursosTxtHorarioDesdeMinutos.setText("00");

        jLabel111.setText("De:");

        jLabel112.setText("A:");

        CursosTxtHorarioHastaHora.setText("16");

        jLabel113.setText(":");

        CursosTxtHorarioHastaMinutos.setText("00");

        CursosBtnHorarioNuevo.setText("+");

        CursosCheckAnexarHorarioACurso.setBackground(new java.awt.Color(255, 255, 102));
        CursosCheckAnexarHorarioACurso.setText("Anexar horario a curso");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel51)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CursosCBProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel109)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CursosCBDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel111)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CursosTxtHorarioDesdeHora, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel110)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CursosTxtHorarioDesdeMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel112)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CursosTxtHorarioHastaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel113)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CursosTxtHorarioHastaMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel108)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CursosCBHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CursosBtnHorarioNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CursosCheckAnexarHorarioACurso)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel108)
                    .addComponent(CursosCBHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CursosBtnHorarioNuevo)
                        .addComponent(CursosCheckAnexarHorarioACurso)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(CursosCBProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel109)
                    .addComponent(CursosCBDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CursosTxtHorarioDesdeHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel110)
                    .addComponent(CursosTxtHorarioDesdeMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel111)
                    .addComponent(jLabel112)
                    .addComponent(CursosTxtHorarioHastaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel113)
                    .addComponent(CursosTxtHorarioHastaMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CursosjPanel4Layout = new javax.swing.GroupLayout(CursosjPanel4);
        CursosjPanel4.setLayout(CursosjPanel4Layout);
        CursosjPanel4Layout.setHorizontalGroup(
            CursosjPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CursosjPanel4Layout.createSequentialGroup()
                .addGroup(CursosjPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CursosjPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CursosjPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CursosjPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(CursosjPanel4Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(jSeparator1))
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(CursosjPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(CursosjPanel4Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(CursosverAlumnosAfectadosBtn))
                            .addComponent(jScrollPane3)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 312, Short.MAX_VALUE)))
                    .addGroup(CursosjPanel4Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(CursosguardarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CursosaceptarCargarBtn)
                        .addGap(18, 18, 18)
                        .addComponent(CursosrestablecerBtn)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        CursosjPanel4Layout.setVerticalGroup(
            CursosjPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CursosjPanel4Layout.createSequentialGroup()
                .addGroup(CursosjPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CursosjPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(CursosjPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CursosjPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CursosverAlumnosAfectadosBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CursosjPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CursosaceptarCargarBtn)
                    .addComponent(CursosrestablecerBtn)
                    .addComponent(CursosguardarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        CursosjTabbCursos.addTab("ABM Cursos", CursosjPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        CursosjTabbCursos.addTab("Horarios", jPanel5);

        javax.swing.GroupLayout tabCursosLayout = new javax.swing.GroupLayout(tabCursos);
        tabCursos.setLayout(tabCursosLayout);
        tabCursosLayout.setHorizontalGroup(
            tabCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCursosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CursosjTabbCursos)
                .addContainerGap())
        );
        tabCursosLayout.setVerticalGroup(
            tabCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCursosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CursosjTabbCursos)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tabCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tabCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CursosguardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CursosguardarBtnActionPerformed
        try{
            Cursos c = new Cursos();
            c.setActivo(CursosjCheckBox1.isSelected()?1:0);
            c.setCantidad_cuotas(Integer.valueOf(CursoscantidadCuotasTxt.getText()));
            c.setCapacidad_aula(Integer.valueOf(CursoscapacidadAulaTxt.getText()));
            c.setCarga_horaria(CursoscargaHorariaHorasTxt.getText()+":"+CursoscargaHorariaMinutosTxt.getText()+":00");
            c.setColor_fondo(CursoscolorFondoTxt.getText());
            c.setColor_fuente(CursoscolorFuenteTxt.getText());
            c.setCosto_inscripcion(Double.valueOf(CursoscostoInscripcionTxt.getText()));
            c.setCuota_sugerida(Double.valueOf(CursoscuotaSugeridaTxt.getText()));
            c.setDuracion(Integer.valueOf(CursosduracionCursoMesesTxt.getText()));
            c.setFecha_fin(jXDatePicker5.getEditor().getText());
            c.setFecha_inicio(jXDatePicker4.getEditor().getText());
            c.setG_profesor(Double.valueOf(CursosgProfesorTxt.getText()));
            c.setIdNombreCurso((new CursosNombres()).obtenerIdSegunNombre(String.valueOf(CursosCBNombreCurso.getSelectedItem())));
            c.setNombre(String.valueOf(CursosCBNombreCurso.getSelectedItem())+ " " +String.valueOf(CursosCBCicloLectivo.getSelectedItem()));
            c.setObservaciones(String.valueOf(CursosCBCicloLectivo.getSelectedItem()));
            c.setRequisitos(CursosrequisitosPrvTxt.getText());
            c.setTitulo(CursostituloTxt.getText());
            c.guardarComoNueva();
            if(CursosCheckAnexarHorarioACurso.isSelected()){
                Horarios h = new Horarios();
                h.setId_curso(c.getIdUltimoCurso());
                String dia = String.valueOf(CursosCBProfesores.getSelectedItem()),
                dH = CursosTxtHorarioDesdeHora.getText(),
                dM = CursosTxtHorarioDesdeMinutos.getText(),
                aH = CursosTxtHorarioHastaHora.getText(),
                aM = CursosTxtHorarioHastaMinutos.getText();
                h.setHorario(dia,dH,dM,aH,aM);
            }
            JOptionPane.showMessageDialog(null, "Curso guardado Correctamente");
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(null, "Error, el curso no pudo ser guardado, revise que todos los campos hayan sido completados. "+ ex.getMessage());
        } catch (IllegalAccessException ex) {
            JOptionPane.showMessageDialog(null, "Error, el curso no pudo ser guardado, revise que todos los campos hayan sido completados. "+ ex.getMessage());
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(null, "Error, el curso no pudo ser guardado, revise que todos los campos hayan sido completados. "+ ex.getMessage());
        } catch (InvocationTargetException ex) {
            JOptionPane.showMessageDialog(null, "Error, el curso no pudo ser guardado, revise que todos los campos hayan sido completados. "+ ex.getMessage());
        }
    }//GEN-LAST:event_CursosguardarBtnActionPerformed

    private void CursosrestablecerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CursosrestablecerBtnActionPerformed
        CursosjCheckBox1.setSelected(false);
        CursoscantidadCuotasTxt.setText("");
        CursoscapacidadAulaTxt.setText("");
        CursoscargaHorariaHorasTxt.setText("");
        CursoscargaHorariaMinutosTxt.setText("");
        CursoscolorFondoTxt.setText("");
        CursoscolorFuenteTxt.setText("");
        CursoscostoInscripcionTxt.setText("");
        CursoscuotaSugeridaTxt.setText("");
        CursosduracionCursoMesesTxt.setText("");
        CursosgProfesorTxt.setText("");
        CursosrequisitosPrvTxt.setText("");
        CursostituloTxt.setText("");
    }//GEN-LAST:event_CursosrestablecerBtnActionPerformed

    private void CursosaceptarCargarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CursosaceptarCargarBtnActionPerformed
        CursosguardarBtnActionPerformed(evt);
        CursosrestablecerBtnActionPerformed(evt);
    }//GEN-LAST:event_CursosaceptarCargarBtnActionPerformed

    private void CursoscolorFuenteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CursoscolorFuenteBtnActionPerformed
        abrirDialogoSelecColor(CursoscolorFuenteTxt);
    }//GEN-LAST:event_CursoscolorFuenteBtnActionPerformed

    private void CursoscolorFondoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CursoscolorFondoBtnActionPerformed
        abrirDialogoSelecColor(CursoscolorFondoTxt);
    }//GEN-LAST:event_CursoscolorFondoBtnActionPerformed

    private void CursosjList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CursosjList2MouseClicked
        if (!CursosjList2.getSelectedValue().equals(null)){
            String color;
            try {
                String item = String.valueOf(CursosjList2.getSelectedValue());
                int idCurso = Integer.valueOf(item.substring(item.indexOf("<")+1, item.indexOf(">")));
                Cursos c = new Cursos();
                c.obtenerCursoSegunIdCurso(idCurso);
                CursosjCheckBox1.setSelected(c.getActivo()==1?true:false);
                CursoscantidadCuotasTxt.setText(String.valueOf(c.getCantidad_cuotas()));
                CursoscapacidadAulaTxt.setText(String.valueOf(c.getCapacidad_aula()));
                CursoscargaHorariaHorasTxt.setText(c.getCarga_horaria().substring(0,2));
                CursoscargaHorariaMinutosTxt.setText(c.getCarga_horaria().substring(3,5));

                color = c.getColor_fondo().startsWith("#")?c.getColor_fondo():"#"+c.getColor_fondo();
                color = color.toUpperCase();
                CursoscolorFondoTxt.setText(color);
                CursoscolorFondoTxt.setBackground(Color.decode(color));

                color = c.getColor_fuente().startsWith("#")?c.getColor_fuente():"#"+c.getColor_fuente();
                color = color.toUpperCase();
                CursoscolorFuenteTxt.setText(color);
                CursoscolorFuenteTxt.setBackground(Color.decode(color));

                CursoscostoInscripcionTxt.setText(String.valueOf(c.getCosto_inscripcion()));
                CursoscuotaSugeridaTxt.setText(String.valueOf(c.getCuota_sugerida()));
                CursosduracionCursoMesesTxt.setText(String.valueOf(c.getDuracion()));
                jXDatePicker5.getEditor().setText(c.getFecha_fin());
                jXDatePicker4.getEditor().setText(c.getFecha_inicio());
                CursosgProfesorTxt.setText(String.valueOf(c.getG_profesor()));
                CursosCBNombreCurso.setSelectedItem((new CursosNombres()).obtenerNombreSegunId(c.getIdNombreCurso()));
                CursosCBCicloLectivo.setSelectedItem(c.getObservaciones());
                CursosrequisitosPrvTxt.setText(c.getRequisitos());
                CursostituloTxt.setText(c.getTitulo());
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_CursosjList2MouseClicked

    private void cursosRbTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursosRbTodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cursosRbTodosActionPerformed

    private void cursosRbTodosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cursosRbTodosMouseClicked
        obtenerCursos();
    }//GEN-LAST:event_cursosRbTodosMouseClicked

    private void cursosRbAnioAntMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cursosRbAnioAntMouseClicked
        obtenerCursos();
    }//GEN-LAST:event_cursosRbAnioAntMouseClicked

    private void cursosRbAnioSigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cursosRbAnioSigMouseClicked
        obtenerCursos();
    }//GEN-LAST:event_cursosRbAnioSigMouseClicked

    private void cursosRbAnioActualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cursosRbAnioActualMouseClicked
        obtenerCursos();
    }//GEN-LAST:event_cursosRbAnioActualMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CursosBtnHorarioNuevo;
    private javax.swing.JComboBox CursosCBCicloLectivo;
    private javax.swing.JComboBox CursosCBDias;
    private javax.swing.JComboBox CursosCBHorarios;
    private javax.swing.JComboBox<String> CursosCBNombreCurso;
    private javax.swing.JComboBox CursosCBProfesores;
    private javax.swing.JCheckBox CursosCheckAnexarHorarioACurso;
    private javax.swing.ButtonGroup CursosSelecAnioParaCursos;
    private javax.swing.JTextField CursosTxtHorarioDesdeHora;
    private javax.swing.JTextField CursosTxtHorarioDesdeMinutos;
    private javax.swing.JTextField CursosTxtHorarioHastaHora;
    private javax.swing.JTextField CursosTxtHorarioHastaMinutos;
    private javax.swing.JButton CursosaceptarCargarBtn;
    private javax.swing.JButton CursosagregarCursoBtn;
    private javax.swing.JTextField CursoscantidadCuotasTxt;
    private javax.swing.JTextField CursoscapacidadAulaTxt;
    private javax.swing.JTextField CursoscargaHorariaHorasTxt;
    private javax.swing.JTextField CursoscargaHorariaMinutosTxt;
    private javax.swing.JButton CursoscolorFondoBtn;
    private javax.swing.JTextField CursoscolorFondoTxt;
    private javax.swing.JButton CursoscolorFuenteBtn;
    private javax.swing.JTextField CursoscolorFuenteTxt;
    private javax.swing.JTextField CursoscostoInscripcionTxt;
    private javax.swing.JTextField CursoscuotaSugeridaTxt;
    private javax.swing.JTextField CursosduracionCursoMesesTxt;
    private javax.swing.JTextField CursosgProfesorTxt;
    private javax.swing.JButton CursosguardarBtn;
    private javax.swing.JCheckBox CursosjCheckBox1;
    private javax.swing.JList<String> CursosjList2;
    private javax.swing.JPanel CursosjPanel4;
    private javax.swing.JPanel CursosjPanel8;
    private javax.swing.JTabbedPane CursosjTabbCursos;
    private javax.swing.JTextField CursosrequisitosPrvTxt;
    private javax.swing.JButton CursosrestablecerBtn;
    private javax.swing.JTextField CursostituloTxt;
    private javax.swing.JButton CursosverAlumnosAfectadosBtn;
    private javax.swing.JRadioButton cursosRbAnioActual;
    private javax.swing.JRadioButton cursosRbAnioAnt;
    private javax.swing.JRadioButton cursosRbAnioSig;
    private javax.swing.JRadioButton cursosRbTodos;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker4;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker5;
    private javax.swing.JPanel tabCursos;
    // End of variables declaration//GEN-END:variables
}
